version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dresspass
      MYSQL_DATABASE: dressdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: dresspass
      DB_NAME: dressdb
    depends_on:
      - db
    ports:
      - "8080:8080"   

  frontend:
    build: ./frontend
    working_dir: /app
    command: npm install && npm run dev -- --host 0.0.0.0
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app:ro
      - /app/node_modules
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"   
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
