version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_DB}:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: dev
    ports:
       - "${PORT_BACKEND}:8080" #Only for local
    depends_on:
      - mysql
    volumes:
      - images-data:/app/public/images

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT_NGINX}:80"
    depends_on:
      - backend
    volumes:
      - images-data:/app/public/images

volumes:
  db-data:
  images-data: