spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:dresscode}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      org.springframework: DEBUG

jwt:
  secret: ${JWT_SECRET:eT8jc7PWmB6U1SxBUgzeVpNQ8BzOE+h8fM4EUUitq80=}
  expiration: 3600000

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST:db}:3306/${DB_NAME:dressdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:dresspass}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET:eT8jc7PWmB6U1SxBUgzeVpNQ8BzOE+h8fM4EUUitq80=}
  expiration: 3600000
